export const idToSubscribe: IdToSubscribe[] = [
  { id: "telegram.0.communicate.request", name: "telegram" },
  { id: "javascript.0.Geraete.WetterCom.temp_value", name: "Aussentemperatur" },
  { id: "trashschedule.0.type.json", name: "trash", key: "trash" },
  { id: "alexa-shoppinglist.0.list_activ", name: "shoppingList", key: "shoppingList" },
  { id: "0_userdata.0.Urlaub.Urlaub_aktiv", name: "", key: "urlaubAktiv" },
  // Timer
  { id: "alexa-timer-vis.0.all_Timer.alive", key: "showTimerCard" },
  // Timer 1
  { id: "alexa-timer-vis.0.timer1.string_2", name: "", key: "timer", subKey: "timer1,string" },
  { id: "alexa-timer-vis.0.timer1.TimeEnd", name: "", key: "timer", subKey: "timer1,timeEnd" },
  { id: "alexa-timer-vis.0.timer1.TimeStart", name: "", key: "timer", subKey: "timer1,timeStart" },
  { id: "alexa-timer-vis.0.timer1.InputDeviceName", name: "", key: "timer", subKey: "timer1,device" },
  { id: "alexa-timer-vis.0.timer1.name", name: "", key: "timer", subKey: "timer1,name" },
  // Timer 2
  { id: "alexa-timer-vis.0.timer2.string_2", name: "", key: "timer", subKey: "timer2,string" },
  { id: "alexa-timer-vis.0.timer2.TimeEnd", name: "", key: "timer", subKey: "timer2,timeEnd" },
  { id: "alexa-timer-vis.0.timer2.TimeStart", name: "", key: "timer", subKey: "timer2,timeStart" },
  { id: "alexa-timer-vis.0.timer2.InputDeviceName", name: "", key: "timer", subKey: "timer2,device" },
  { id: "alexa-timer-vis.0.timer2.name", name: "", key: "timer", subKey: "timer2,name" },
  // Timer 3
  { id: "alexa-timer-vis.0.timer3.string_2", name: "", key: "timer", subKey: "timer3,string" },
  { id: "alexa-timer-vis.0.timer3.TimeEnd", name: "", key: "timer", subKey: "timer3,timeEnd" },
  { id: "alexa-timer-vis.0.timer3.TimeStart", name: "", key: "timer", subKey: "timer3,timeStart" },
  { id: "alexa-timer-vis.0.timer3.InputDeviceName", name: "", key: "timer", subKey: "timer3,device" },
  { id: "alexa-timer-vis.0.timer3.name", name: "", key: "timer", subKey: "timer3,name" },
  // Timer 4
  { id: "alexa-timer-vis.0.timer4.string_2", name: "", key: "timer", subKey: "timer4,string" },
  { id: "alexa-timer-vis.0.timer4.TimeEnd", name: "", key: "timer", subKey: "timer4,timeEnd" },
  { id: "alexa-timer-vis.0.timer4.TimeStart", name: "", key: "timer", subKey: "timer4,timeStart" },
  { id: "alexa-timer-vis.0.timer4.InputDeviceName", name: "", key: "timer", subKey: "timer4,device" },
  { id: "alexa-timer-vis.0.timer4.name", name: "", key: "timer", subKey: "timer4,name" },
  // Fenster
  { id: "0_userdata.0.Fenster.Sind_Fenster_offen", name: "", key: "fensterOffen" },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster klein open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,ecke",
  },
  {
    id: "alias.0.Gäste WC.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "gaesteWc,rechts",
  },
  {
    id: "alias.0.Gäste WC.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "gaesteWc,links",
  },
  {
    id: "zigbee.0.00158d0003cb431e.opened",
    name: "",
    key: "fenster",
    subKey: "buero,fenster",
  },
  {
    id: "alias.0.Schlafzimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "schlafen,fenster",
  },
  {
    id: "alias.0.Schlafzimmer.Xiaomi AqaraSensoren.Tür open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "schlafen,tuer",
  },
  {
    id: "alias.0.Keller.Xiaomi AqaraSensoren.Tür open.Kellertür open",
    name: "",
    key: "fenster",
    subKey: "keller,tuer",
  },
  {
    id: "alias.0.Kinderzimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "kinderzimmer,fenster",
  },
  {
    id: "alias.0.Bad.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "bad,fenster",
  },
  {
    id: "alias.0.Gästezimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "gaestezimmer,fenster",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,links",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,rechts",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster mitte open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,mittig",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster klein open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,ecke",
  },
  {
    id: "alias.0.Esszimmer.Xiaomi AqaraSensoren.Links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "esszimmer,links",
  },
  {
    id: "alias.0.Esszimmer.Xiaomi AqaraSensoren.Rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "esszimmer,rechts",
  },
  {
    id: "alias.0.Küche.Xiaomi AqaraSensoren.Tür open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "kueche,tuer",
  },
  {
    id: "alias.0.Küche.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "kueche,fenster",
  },
  {
    id: "alias.0.Abstellraum.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "abstellraum,fenster",
  },
  {
    id: "alias.0.Abstellraum OG.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "abstellraumog,links",
  },
  {
    id: "alias.0.Abstellraum OG.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "abstellraumog,rechts",
  },
  {
    id: "alias.0.Dachboden.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "dachboden,links",
  },
  {
    id: "alias.0.Dachboden.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "dachboden,rechts",
  },
  {
    id: "alias.0.Flur.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "flur,links",
  },
  {
    id: "alias.0.Flur.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "flur,rechts",
  },
  {
    id: "alias.0.Keller.Xiaomi AqaraSensoren.Keller Treppe.Fenster.KellerTreppe Fenster",
    name: "",
    key: "fenster",
    subKey: "keller,flurFenster",
  },

  // Rolladen
  { id: "s7.1.DBs.DB1.B150", name: "", key: "rolladen", subKey: "wohnzimmer,mittig" },
  { id: "s7.1.DBs.DB1.B152", name: "", key: "rolladen", subKey: "wohnzimmer,ecke" },
  { id: "s7.1.DBs.DB1.B159", name: "", key: "rolladen", subKey: "wohnzimmer,links" },
  { id: "s7.1.DBs.DB1.B157", name: "", key: "rolladen", subKey: "wohnzimmer,rechts" },
  { id: "s7.1.DBs.DB1.B129", name: "", key: "rolladen", subKey: "kueche,tuer" },
  { id: "s7.1.DBs.DB1.B145", name: "", key: "rolladen", subKey: "kueche,fenster" },
  { id: "s7.1.DBs.DB1.B136", name: "", key: "rolladen", subKey: "esszimmer,links" /*Einfach links für angenommen als Rollade*/ },
  { id: "s7.1.DBs.DB1.B164", name: "", key: "rolladen", subKey: "kinderzimmer,fenster" },
  { id: "s7.1.DBs.DB1.B169", name: "", key: "rolladen", subKey: "schlafen,tuer" },
  { id: "s7.2.DBs.DB1.B065", name: "", key: "rolladen", subKey: "schlafen,fenster" },
  { id: "s7.2.DBs.DB1.B073", name: "", key: "rolladen", subKey: "abstellraumog,links" },
  { id: "s7.2.DBs.DB1.B057", name: "", key: "rolladen", subKey: "abstellraumog,rechts" },
  { id: "s7.2.DBs.DB1.B078", name: "", key: "rolladen", subKey: "bad,fenster" },
  { id: "s7.2.DBs.DB1.B150", name: "", key: "rolladen", subKey: "gaestezimmer,fenster" },
  // Sonnenuntergang
  { id: "0_userdata.0.Rolladen.Zeit_Rollade_auto_herunter", key: "sonnenuntergang" },
];
