export const idToSubscribe: IdToSubscribe[] = [
  { id: "javascript.0.Geraete.WetterCom.temp_value", name: "Aussentemperatur" },
  { id: "trashschedule.0.type.json", name: "trash", key: "trash" },
  { id: "alexa-shoppinglist.0.list_activ", name: "shoppingList", key: "shoppingList" },
  { id: "0_userdata.0.Urlaub.Urlaub_aktiv", name: "", key: "urlaubAktiv" },
  // Timer
  { id: "alexa-timer-vis.0.all_Timer.alive", key: "showTimerCard" },
  // Timer 1
  { id: "alexa-timer-vis.0.timer1.string_2", name: "", key: "timer", subKey: "timer1,string" },
  { id: "alexa-timer-vis.0.timer1.TimeEnd", name: "", key: "timer", subKey: "timer1,timeEnd" },
  { id: "alexa-timer-vis.0.timer1.TimeStart", name: "", key: "timer", subKey: "timer1,timeStart" },
  { id: "alexa-timer-vis.0.timer1.InputDeviceName", name: "", key: "timer", subKey: "timer1,device" },
  { id: "alexa-timer-vis.0.timer1.name", name: "", key: "timer", subKey: "timer1,name" },
  // Timer 2
  { id: "alexa-timer-vis.0.timer2.string_2", name: "", key: "timer", subKey: "timer2,string" },
  { id: "alexa-timer-vis.0.timer2.TimeEnd", name: "", key: "timer", subKey: "timer2,timeEnd" },
  { id: "alexa-timer-vis.0.timer2.TimeStart", name: "", key: "timer", subKey: "timer2,timeStart" },
  { id: "alexa-timer-vis.0.timer2.InputDeviceName", name: "", key: "timer", subKey: "timer2,device" },
  { id: "alexa-timer-vis.0.timer2.name", name: "", key: "timer", subKey: "timer2,name" },
  // Timer 3
  { id: "alexa-timer-vis.0.timer3.string_2", name: "", key: "timer", subKey: "timer3,string" },
  { id: "alexa-timer-vis.0.timer3.TimeEnd", name: "", key: "timer", subKey: "timer3,timeEnd" },
  { id: "alexa-timer-vis.0.timer3.TimeStart", name: "", key: "timer", subKey: "timer3,timeStart" },
  { id: "alexa-timer-vis.0.timer3.InputDeviceName", name: "", key: "timer", subKey: "timer3,device" },
  { id: "alexa-timer-vis.0.timer3.name", name: "", key: "timer", subKey: "timer3,name" },
  // Timer 4
  { id: "alexa-timer-vis.0.timer4.string_2", name: "", key: "timer", subKey: "timer4,string" },
  { id: "alexa-timer-vis.0.timer4.TimeEnd", name: "", key: "timer", subKey: "timer4,timeEnd" },
  { id: "alexa-timer-vis.0.timer4.TimeStart", name: "", key: "timer", subKey: "timer4,timeStart" },
  { id: "alexa-timer-vis.0.timer4.InputDeviceName", name: "", key: "timer", subKey: "timer4,device" },
  { id: "alexa-timer-vis.0.timer4.name", name: "", key: "timer", subKey: "timer4,name" },
  // Fenster
  { id: "0_userdata.0.Fenster.Sind_Fenster_offen", name: "", key: "fensterOffen" },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster klein open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,ecke",
  },
  {
    id: "alias.0.Gäste WC.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "gaesteWc,rechts",
  },
  {
    id: "alias.0.Gäste WC.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "gaesteWc,links",
  },
  {
    id: "zigbee.0.00158d0003cb431e.opened",
    name: "",
    key: "fenster",
    subKey: "buero,fenster",
  },
  {
    id: "alias.0.Schlafzimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "schlafen,fenster",
  },
  {
    id: "alias.0.Schlafzimmer.Xiaomi AqaraSensoren.Tür open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "schlafen,tuer",
  },
  {
    id: "alias.0.Keller.Xiaomi AqaraSensoren.Tür open.Kellertür open",
    name: "",
    key: "fenster",
    subKey: "keller,tuer",
  },
  {
    id: "alias.0.Kinderzimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "kinderzimmer,fenster",
  },
  {
    id: "alias.0.Bad.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "bad,fenster",
  },
  {
    id: "alias.0.Gästezimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "gaestezimmer,fenster",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,links",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,rechts",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster mitte open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,mittig",
  },
  {
    id: "alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster klein open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "wohnzimmer,ecke",
  },
  {
    id: "alias.0.Esszimmer.Xiaomi AqaraSensoren.Links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "esszimmer,links",
  },
  {
    id: "alias.0.Esszimmer.Xiaomi AqaraSensoren.Rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "esszimmer,rechts",
  },
  {
    id: "alias.0.Küche.Xiaomi AqaraSensoren.Tür open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "kueche,tuer",
  },
  {
    id: "alias.0.Küche.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "kueche,fenster",
  },
  {
    id: "alias.0.Abstellraum.Xiaomi AqaraSensoren.Fenster open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "abstellraum,fenster",
  },
  {
    id: "alias.0.Abstellraum OG.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "abstellraumog,links",
  },
  {
    id: "alias.0.Abstellraum OG.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "abstellraumog,rechts",
  },
  {
    id: "alias.0.Dachboden.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "dachboden,links",
  },
  {
    id: "alias.0.Dachboden.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "dachboden,rechts",
  },
  {
    id: "alias.0.Flur.Xiaomi AqaraSensoren.Fenster links open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "flur,links",
  },
  {
    id: "alias.0.Flur.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL",
    name: "",
    key: "fenster",
    subKey: "flur,rechts",
  },
  {
    id: "alias.0.Keller.Xiaomi AqaraSensoren.Keller Treppe.Fenster.KellerTreppe Fenster",
    name: "",
    key: "fenster",
    subKey: "keller,flurFenster",
  },
  // Rolladen
  { id: "s7.1.DBs.DB1.B150", name: "", key: "rolladen", subKey: "wohnzimmer,mittig", saveId: true },
  { id: "s7.1.DBs.DB1.B152", name: "", key: "rolladen", subKey: "wohnzimmer,ecke", saveId: true },
  { id: "s7.1.DBs.DB1.B159", name: "", key: "rolladen", subKey: "wohnzimmer,links", saveId: true },
  { id: "s7.1.DBs.DB1.B157", name: "", key: "rolladen", subKey: "wohnzimmer,rechts", saveId: true },
  { id: "s7.1.DBs.DB1.B129", name: "", key: "rolladen", subKey: "kueche,tuer", saveId: true },
  { id: "s7.1.DBs.DB1.B145", name: "", key: "rolladen", subKey: "kueche,fenster", saveId: true },
  {
    id: "s7.1.DBs.DB1.B136",
    name: "",
    key: "rolladen",
    subKey: "esszimmer,links",
    saveId: true /*Einfach links für angenommen als Rollade*/,
  },
  { id: "s7.1.DBs.DB1.B164", name: "", key: "rolladen", subKey: "kinderzimmer,fenster", saveId: true },
  { id: "s7.1.DBs.DB1.B169", name: "", key: "rolladen", subKey: "schlafen,tuer", saveId: true },
  { id: "s7.2.DBs.DB1.B065", name: "", key: "rolladen", subKey: "schlafen,fenster", saveId: true },
  { id: "s7.2.DBs.DB1.B073", name: "", key: "rolladen", subKey: "abstellraumog,links", saveId: true },
  { id: "s7.2.DBs.DB1.B057", name: "", key: "rolladen", subKey: "abstellraumog,rechts", saveId: true },
  { id: "s7.2.DBs.DB1.B078", name: "", key: "rolladen", subKey: "bad,fenster", saveId: true },
  { id: "s7.2.DBs.DB1.B150", key: "rolladen", subKey: "gaestezimmer,fenster", saveId: true },
  // Sonnenuntergang
  { id: "0_userdata.0.Rolladen.Zeit_Rollade_auto_herunter", key: "sonnenuntergang" },
  // Zeitversatz Rolladen Auto herunter fahren
  {
    id: "0_userdata.0.Rolladen.Esszimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "esszimmer, linksDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Küche.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "kueche, fensterDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Schlafzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "schlafen, fensterDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Schlafzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "schlafen, tuerDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Kinderzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "kinderzimmer, fensterDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Bad.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "bad, fensterDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, eckeDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, linksDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, mittigDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, rechtsDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Küche.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(Tür)",
    key: "shutterAutoDownTime",
    subKey: "kueche, tuerDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(links)",
    key: "shutterAutoDownTime",
    subKey: "abstellraumog, linksDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(rechts)",
    key: "shutterAutoDownTime",
    subKey: "abstellraumog, rechtsDelay",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Gästezimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
    key: "shutterAutoDownTime",
    subKey: "gaestezimmer, fensterDelay",
    saveId: true,
  },
  // Auto herunterfahren Rolladen
  {
    id: "0_userdata.0.Rolladen.Esszimmer.Esszimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "esszimmer, linksAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Esszimmer.Esszimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "esszimmer, linksAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Küche.Fenster_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "kueche, fensterAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Schlafzimmer.Schlafzimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "schlafen, tuerAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Kinderzimmer.Rollade_automisch_runter",
    key: "shutterAutoDownTime",
    subKey: "kinderzimmer, fensterAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Bad.Bad_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "bad, fensterAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, eckeAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, linksAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, mittigAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "wohnzimmer, rechtsAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Küche.Tür_Rolladen_Zeitsteuerung",
    key: "shutterAutoDownTime",
    subKey: "kueche, tuerAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Abstellraum_OG_links_Rolladen_Zeitsteuerung_aktiv",
    key: "shutterAutoDownTime",
    subKey: "abstellraumog, linksAuto",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Abstellraum_OG_rechts_Rolladen_Zeitsteuerung_aktiv",
    key: "shutterAutoDownTime",
    subKey: "abstellraumog, rechtsAuto",
    saveId: true,
  },
  // Zeit Auto hochfahren Rolladen
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "wohnzimmer, eckeAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "wohnzimmer, linksAutoUp",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "wohnzimmer, mittigAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "wohnzimmer, rechtsAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Schlafzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "schlafen, tuerAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Schlafzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "schlafen, fensterAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Küche.Zeit_Rollade_hoch_Fenster",
    key: "shutterAutoUp",
    subKey: "kueche, fensterAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Küche.Zeit_Rollade_hoch_Tür",
    key: "shutterAutoUp",
    subKey: "kueche, tuerAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Kinderzimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "kinderzimmer, fensterAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Esszimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "esszimmer, linksAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Bad.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "bad, fensterAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Zeit_Rollade_hoch_rechts",
    key: "shutterAutoUp",
    subKey: "abstellraumog, rechtsAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Zeit_Rollade_hoch_links",
    key: "shutterAutoUp",
    subKey: "abstellraumog, linksAutoUpTime",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Gästezimmer.Zeit_Rollade_hoch",
    key: "shutterAutoUp",
    subKey: "gaestezimmer, fensterAutoUpTime",
    saveId: true,
  },
  // Auto hoch aktiv
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Auto_hoch_links",
    key: "shutterAutoUp",
    subKey: "abstellraumog, fensterAutoUp",
    saveId: true,
  },
  {
    id: "0_userdata.0.Rolladen.Abstellraum_OG.Auto_hoch_rechts",
    key: "shutterAutoUp",
    subKey: "abstellraumog, fensterAutoUp",
    saveId: true,
  },
];
