export enum HTMLInputTypesEnum {
  text = "text",
  password = "password",
  email = "email",
  number = "number",
  checkbox = "checkbox",
  radio = "radio",
  file = "file",
  submit = "submit",
  reset = "reset",
  button = "button",
  hidden = "hidden",
  date = "date",
  "datetime-local" = "datetime-local",
  month = "month",
  week = "week",
  time = "time",
  url = "url",
  search = "search",
  tel = "tel",
  color = "color",
}
