export type RoutePath = (typeof routes)[keyof typeof routes]["path"];
export type TRoute = (typeof routes)[keyof typeof routes];

export const routes = {
  home: { path: "/", name: "home" },
  navigation: { path: "/navigation", name: "navigation" },
  alexa: { path: "/alexa", name: "alexa" },
  battery: { path: "/battery", name: "battery" },
  diagrams: { path: "/diagrams", name: "diagrams" },
  lists: { path: "/listen", name: "lists" },
  window: { path: "/fenster", name: "windows" },
  heating: { path: "/heating", name: "heating" },
  heatingControl: { path: "/heizkoerper-steuerung", name: "heatingControl" },
  iobrokerInfo: { path: "/iobroker-info", name: "iobroker-info" },
  calender: { path: "/kalender", name: "calender" },
  light: { path: "/light", name: "light" },
  logs: { path: "/logs", name: "logs" },
  notifications: { path: "/notifications", name: "notifications" },
  pv: { path: "/pv", name: "pv" },
  heatPump: { path: "/heat-pump", name: "heat-pump" },
  energy: { path: "/energy", name: "energy" },
  tanker_koenig: { path: "/tanker_koenig", name: "tanker-koenig" },
  maps: { path: "/karten", name: "maps" },
  recipeApp: { path: "/recipe-app", name: "recipe-app" },
  recipes: { path: "/rezepte", name: "recipes" },
  recipeDetails: { path: "/rezepte/:recipeId", name: "recipe-details" },
  products: { path: "/produkte", name: "products" },
  recipeUnits: { path: "/einheiten", name: "units" },
  recipeCategories: { path: "/rezept-kategorien", name: "recipe-categories" },
  productCategories: { path: "/produkt-kategorien", name: "product-categories" },
  newRecipe: { path: "/neues_rezepte", name: "new-recipe" },
  editRecipe: { path: "/rezepte_bearbeiten/:id?", name: "edit-recipe" },
  finance: { path: "/finance", name: "finance" },
  addresses: { path: "/adressen", name: "addresses" },
  description: { path: "/beschreibung", name: "descriptions" },
  system: { path: "/system", name: "system" },
  wattPilot: { path: "/watt-pilot", name: "wattPilot" },
} as const;
