export const routes = {
  home: { path: "/", name: "home" },
  navigation: { path: "/navigation", name: "navigation" },
  alexa: { path: "/alexa", name: "alexa" },
  battery: { path: "/battery", name: "battery" },
  diagrams: { path: "/diagrams", name: "diagrams" },
  lists: { path: "/listen", name: "lists" },
  window: { path: "/fenster", name: "windows" },
  heating: { path: "/heating", name: "heating" },
  heatingControl: { path: "/heizkoerper-steuerung", name: "heatingControl" },
  iobrokerInfo: { path: "/iobroker-info", name: "iobroker-info" },
  calender: { path: "/kalender", name: "calender" },
  light: { path: "/light", name: "light" },
  logs: { path: "/logs", name: "logs" },
  pv: { path: "/pv", name: "pv" },
  recipeApp: { path: "/recipe-app", name: "recipe-app" },
  recipes: { path: "/rezepte", name: "recipes" },
  recipeDetails: { path: "/rezepte/:recipeId", name: "recipe-details" },
  products: { path: "/produkte", name: "products" },
  recipeUnits: { path: "/einheiten", name: "units" },
  recipeCategories: { path: "/rezept-kategorien", name: "recipe-categories" },
  productCategories: { path: "/produkt-kategorien", name: "product-categories" },
  newRecipe: { path: "/neues_rezepte", name: "new-recipe" },
  editRecipe: { path: "/rezepte_bearbeiten/:id?", name: "edit-recipe" },
  finance: { path: "/finance", name: "finance" },
  addresses: { path: "/adressen", name: "addresses" },
  description: { path: "/beschreibung", name: "descriptions" },
};

export const routing = [
  {
    path: "/",
    component: async () => await import("@/pages/vis/page.vue"),
    children: [
      { component: async () => await import("@/pages/vis/home.vue"), ...routes.home },
      { component: async () => await import("@/pages/vis/navigation.vue"), ...routes.navigation },
      { component: async () => await import("@/pages/vis/alexa.vue"), ...routes.alexa },
      { component: async () => await import("@/pages/vis/battery.vue"), ...routes.battery },
      { component: async () => await import("@/pages/vis/diagrams.vue"), ...routes.diagrams },
      { component: async () => await import("@/pages/vis/lists.vue"), ...routes.lists },
      { component: async () => await import("@/pages/vis/rooms.vue"), ...routes.window },
      { component: async () => await import("@/pages/vis/heating.vue"), ...routes.heating },
      { component: async () => await import("@/pages/vis/heating-control.vue"), ...routes.heatingControl },
      { component: async () => await import("@/pages/vis/iobroker-info.vue"), ...routes.iobrokerInfo },
      { component: async () => await import("@/pages/vis/calendar.vue"), ...routes.calender },
      { component: async () => await import("@/pages/vis/light.vue"), ...routes.light },
      { component: async () => await import("@/pages/vis/logs.vue"), ...routes.logs },
      { component: async () => await import("@/pages/vis/pv.vue"), ...routes.pv },
    ],
  },
  {
    redirect: { name: routes.recipes.name },
    component: async () => await import("@/pages/recipe/recipe-app.vue"),
    ...routes.recipeApp,
    children: [
      {
        component: () => import("@/pages/recipe/products.vue"),
        ...routes.products,
      },
      { component: () => import("@/pages/recipe/units.vue"), ...routes.recipeUnits },
      { component: () => import("@/pages/recipe/product-categories.vue"), ...routes.productCategories },
      { component: () => import("@/pages/recipe/recipe-categories.vue"), ...routes.recipeCategories },
      { component: () => import("@/pages/recipe/recipes.vue"), ...routes.recipes },
      { component: () => import("@/pages/recipe/recipe-details.vue"), props: true, ...routes.recipeDetails },
      { props: true, component: () => import("@/pages/recipe/new-recipe.vue"), ...routes.newRecipe },
      { props: true, component: () => import("@/pages/recipe/edit-recipe.vue"), ...routes.editRecipe },
    ],
  },
  { component: async () => await import("@/pages/finance/listing.vue"), ...routes.finance },
  { component: async () => await import("@/pages/finance/addresses.vue"), ...routes.addresses },
  { component: async () => await import("@/pages/finance/description.vue"), ...routes.description },
  {
    path: "/:pathMatch(.*)*",
    component: async () => await import("@/pages/vis/error-page-not-found.vue"),
  },
];
