import { routes } from "@/router/routes.ts";

export const routing = [
  {
    path: "/",
    component: async () => await import("@/pages/vis/page.vue"),
    children: [
      { component: async () => await import("@/pages/vis/home.vue"), ...routes.home },
      { component: async () => await import("@/pages/vis/navigation.vue"), ...routes.navigation },
      { component: async () => await import("@/pages/vis/alexa.vue"), ...routes.alexa },
      { component: async () => await import("@/pages/vis/battery.vue"), ...routes.battery },
      { component: async () => await import("@/pages/vis/diagrams.vue"), ...routes.diagrams },
      { component: async () => await import("@/pages/vis/lists.vue"), ...routes.lists },
      { component: async () => await import("@/pages/vis/rooms.vue"), ...routes.window },
      { component: async () => await import("@/pages/vis/heating.vue"), ...routes.heating },
      { component: async () => await import("@/pages/vis/heating-control.vue"), ...routes.heatingControl },
      { component: async () => await import("@/pages/vis/iobroker-updates-and-news.vue"), ...routes.iobrokerInfo },
      { component: async () => await import("@/pages/vis/calendar.vue"), ...routes.calender },
      { component: async () => await import("@/pages/vis/light.vue"), ...routes.light },
      { component: async () => await import("@/pages/vis/logs.vue"), ...routes.logs },
      { component: async () => await import("@/pages/vis/pv.vue"), ...routes.pv },
      { component: async () => await import("@/pages/vis/tankerkoenig.vue"), ...routes.tanker_koenig },
      { component: async () => await import("@/pages/vis/energy.vue"), ...routes.energy },
      { component: async () => await import("@/pages/vis/maps.vue"), ...routes.maps },
      { component: async () => await import("@/pages/vis/heat-pump.vue"), ...routes.heatPump },
      { component: async () => await import("@/pages/vis/system.vue"), ...routes.system },
      { component: async () => await import("@/pages/vis/watt-pilot.vue"), ...routes.wattPilot },
      { component: async () => await import("@/pages/vis/notifications.vue"), ...routes.notifications },
    ],
  },
  {
    redirect: { name: routes.recipes.name },
    component: async () => await import("@/pages/recipe/recipe-app.vue"),
    ...routes.recipeApp,
    children: [
      {
        component: () => import("@/pages/recipe/products.vue"),
        ...routes.products,
      },
      { component: () => import("@/pages/recipe/units.vue"), ...routes.recipeUnits },
      { component: () => import("@/pages/recipe/product-categories.vue"), ...routes.productCategories },
      { component: () => import("@/pages/recipe/recipe-categories.vue"), ...routes.recipeCategories },
      { component: () => import("@/pages/recipe/recipes.vue"), ...routes.recipes },
      { component: () => import("@/pages/recipe/recipe-details.vue"), props: true, ...routes.recipeDetails },
      { props: true, component: () => import("@/pages/recipe/new-recipe.vue"), ...routes.newRecipe },
      { props: true, component: () => import("@/pages/recipe/edit-recipe.vue"), ...routes.editRecipe },
    ],
  },
  { component: async () => await import("@/pages/finance/listing.vue"), ...routes.finance },
  { component: async () => await import("@/pages/finance/addresses.vue"), ...routes.addresses },
  { component: async () => await import("@/pages/finance/description.vue"), ...routes.description },
  {
    path: "/:pathMatch(.*)*",
    component: async () => await import("@/pages/vis/error-page-not-found.vue"),
  },
];
