const routing = {
  home: { path: "", name: "home" },
  navigation: { path: "/index", name: "index" },
  alexa: { path: "/alexa", name: "alexa" },
  battery: { path: "/battery", name: "battery" },
  diagrams: { path: "/diagrams", name: "diagrams" },
  lists: { path: "/listen", name: "lists" },
  window: { path: "/fenster", name: "windows" },
  heating: { path: "/heating", name: "heating" },
  iobrokerInfo: { path: "/iobroker-info", name: "iobroker-info" },
  calender: { path: "/kalender", name: "calender" },
  light: { path: "/light", name: "light" },
  logs: { path: "/logs", name: "logs" },
  pv: { path: "/pv", name: "pv" },
  recipeApp: { path: "/recipe-app", name: "recipe-app" },
  recipe: { path: "/rezepte", name: "recipe" },
  recipeDetails: { path: "/rezepte/:recipeId", name: "recipe-details" },
  recipeProducts: { path: "/produkte", name: "products" },
  recipeUnits: { path: "/einheiten", name: "units" },
  recipeCategories: { path: "/kategorien", name: "categories" },
  newRecipe: { path: "/neues_rezepte/:id?", name: "new-recipe" },
  finance: { path: "/finance", name: "finance" },
  addresses: { path: "/adressen", name: "addresses" },
  description: { path: "/beschreibung", name: "descriptions" },
};

export const routes = [
  {
    path: "/",
    component: async () => await import("@/pages/page.vue"),
    children: [
      { component: async () => await import("@/pages/home.vue"), ...routing.home },
      { component: async () => await import("@/pages/navigation.vue"), ...routing.navigation },
      { component: async () => await import("@/pages/alexa.vue"), ...routing.alexa },
      { component: async () => await import("@/pages/battery.vue"), ...routing.battery },
      { component: async () => await import("@/pages/diagrams.vue"), ...routing.diagrams },
      { component: async () => await import("@/pages/lists.vue"), ...routing.lists },
      { component: async () => await import("@/pages/rooms.vue"), ...routing.window },
      { component: async () => await import("@/pages/heating.vue"), ...routing.heating },
      { component: async () => await import("@/pages/iobroker-info.vue"), ...routing.iobrokerInfo },
      { component: async () => await import("@/pages/calendar.vue"), ...routing.calender },
      { component: async () => await import("@/pages/light.vue"), ...routing.light },
      { component: async () => await import("@/pages/logs.vue"), ...routing.logs },
      { component: async () => await import("@/pages/pv.vue"), ...routing.pv },
    ],
  },
  {
    redirect: { name: routing.recipe.name },
    component: async () => await import("@/pages/recipe/recipe-app.vue"),
    ...routing.recipeApp,
    children: [
      { component: () => import("@/pages/recipe/products.vue"), ...routing.recipeProducts },
      { component: () => import("@/pages/recipe/units.vue"), ...routing.recipeUnits },
      { component: () => import("@/pages/recipe/categories.vue"), ...routing.recipeCategories },
      {
        component: () => import("@/pages/recipe/recipe.vue"),
        children: [{ component: () => import("@/pages/recipe/recipe-details.vue"), props: true, ...routing.recipeDetails }],
        ...routing.recipe,
      },
      { props: true, component: () => import("@/pages/recipe/new-recipe.vue"), ...routing.newRecipe },
    ],
  },
  { component: async () => await import("@/pages/finance/listing.vue"), ...routing.finance },

  { component: async () => await import("@/pages/finance/addresses.vue"), ...routing.addresses },
  { component: async () => await import("@/pages/finance/description.vue"), ...routing.description },
  {
    path: "/:pathMatch(.*)*",
    component: async () => await import("@/pages/error-page-not-found.vue"),
  },
];
