import { BooleanValue, JsonValue, NumberValue, StringValue } from "@/store/valueClasses.ts";
import {
  AlexaList,
  CalendarDayType,
  HeatingPumpScriptJson,
  HeatingPumpSilentJSON,
  JSONStyle,
  Log,
  TankerkoenigStation,
  TrashType,
  UpdatesAsJSON,
  WattPilotJson,
} from "@/types/types.ts";
import { NewsFeed } from "@/components/section/iobroker";

export const iobrokerTree = {
  logReset: {
    error: new BooleanValue("logparser.0.filters.Error.emptyJson"),
    info: new BooleanValue("logparser.0.filters.Info.emptyJson"),
    warn: new BooleanValue("logparser.0.filters.Warn.emptyJson"),
  },
  heatingTimeSlot: {
    currentTimePeriod: new NumberValue("heatingcontrol.0.vis.RoomValues.CurrentTimePeriod"),
  },
  alexaAction: { alexaSpeak: new StringValue("0_userdata.0.Alexa.Ausgaben_auf_Geräten") },
  pv: {
    feedIn: new NumberValue("modbus.0.holdingRegisters.41079_grid_Power", 0),
    batteryCharging: new NumberValue("modbus.0.holdingRegisters.41069_soc"),
    activeCharging: new NumberValue("modbus.0.holdingRegisters.41067_Active_Power"),
    shellyFeedOut: new NumberValue("shelly.0.shellypro3em#ec6260976f14#1.EM0.TotalActivePower"),
    smallPv: new NumberValue("sonoff.0.Photovoltaik.ENERGY_Power"),
    profit: new NumberValue("0_userdata.0.Photovoltaik.Einnahme_Einspeisung"),
    pvGross: new NumberValue("fronius.0.inverter.1.P"),
    savedMoney: new NumberValue("0_userdata.0.Photovoltaik.Einsparung_durch_PV"),
    energyDaySmall: new NumberValue("sonoff.0.Photovoltaik.ENERGY_Today"),
    energyDayGross: new NumberValue("fronius.0.inverter.1.DAY_ENERGY"),
  },
  system: {
    ramIobrokerUsed: new NumberValue("proxmox.0.lxc.iobroker.mem"),
    ramIobrokerLevel: new NumberValue("proxmox.0.lxc.iobroker.mem_lev"),
    ramIobrokerMax: new NumberValue("proxmox.0.lxc.iobroker.maxmem"),
    cpuIobroker: new NumberValue("proxmox.0.lxc.iobroker.cpu"),
    cpusIobroker: new NumberValue("proxmox.0.lxc.iobroker.cpus"),
    diskIobrokerUsage: new NumberValue("proxmox.0.lxc.iobroker.disk_lev"),
    iobrokerUptime: new NumberValue("proxmox.0.lxc.iobroker.uptime"),
  },
  wattPilot: {
    jsonScriptChargeLevel: new JsonValue<WattPilotJson>("0_userdata.0.Wattpilot.WattpilotScriptJson", ""),
    autoCharging: new BooleanValue("0_userdata.0.Wattpilot.autoCharging"),
    totalCharging: new NumberValue("fronius-wattpilot.0.energyCounterTotal"),
  },
  car: {
    battery: new NumberValue("bluelink.0.KNAFD81A7T6159455.vehicleStatusRaw.Green.BatteryManagement.BatteryRemain.Ratio"),
  },
  batteries: {
    "Shelly Plus Smoke Flur OG": {
      voltage: new NumberValue("shelly.0.shellyplussmoke#a0a3b3e60d84#1.DevicePower0.BatteryVoltage"),
      percent: new NumberValue("shelly.0.shellyplussmoke#a0a3b3e60d84#1.DevicePower0.BatteryPercent"),
      firmware: new BooleanValue("shelly.0.shellyplussmoke#a0a3b3e60d84#1.firmware"),
    },
    "HMIP Buero": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C45.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C45.channels.0.unreach", undefined, true),
    },
    "HMIP Keller Waschen": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C1D.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C1D.channels.0.unreach", undefined, true),
    },
    "HMIP Flur": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A499E347E.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A499E347E.channels.0.unreach", undefined, true),
    },
    "HMIP Gaeste WC": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55A77.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55A77.channels.0.unreach", undefined, true),
    },
    "HMIP Kueche": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A499E49C4.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A499E49C4.channels.0.unreach", undefined, true),
    },
    "HMIP Esszimmer": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55AF0.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55AF0.channels.0.unreach", undefined, true),
    },
    "HMIP Wohnzimmer links": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A499E3491.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A499E3491.channels.0.unreach", undefined, true),
    },
    "HMIP Wohnzimmer rechts": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C21.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C21.channels.0.unreach", undefined, true),
    },
    "HMIP Bad": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55A77.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55A77.channels.0.unreach", undefined, true),
    },
    "HMIP Schlafzimmer": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55AEF.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55AEF.channels.0.unreach", undefined, true),
    },
    "HMIP Kinderzimmer": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55E2C.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55E2C.channels.0.unreach", undefined, true),
    },
    "HMIP Gaestezimmer": {
      lowBat: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C2A.channels.0.lowBat"),
      available: new BooleanValue("hmip.0.devices.3014F711A000201A49A55C2A.channels.0.unreach", undefined, true),
    },
    xioami_cellar_door: {
      percent: new NumberValue("zigbee.0.00158d00045efc35.battery"),
      voltage: new NumberValue("zigbee.0.00158d00045efc35.voltage"),
      available: new BooleanValue("zigbee.0.00158d00045efc35.available"),
    },
    xioami_cellar_stair_window: {
      percent: new NumberValue("zigbee.0.00158d0002e3425d.battery"),
      voltage: new NumberValue("zigbee.0.00158d0002e3425d.voltage"),
      available: new BooleanValue("zigbee.0.00158d0002e3425d.available"),
    },
    xioami_office_window: {
      percent: new NumberValue("zigbee.0.00158d0003cb431e.battery"),
      voltage: new NumberValue("zigbee.0.00158d0003cb431e.voltage"),
      available: new BooleanValue("zigbee.0.00158d0003cb431e.available"),
    },
    xioami_housedoor_right: {
      percent: new NumberValue("zigbee.0.00158d00049fd9ee.battery"),
      voltage: new NumberValue("zigbee.0.00158d00049fd9ee.voltage"),
      available: new BooleanValue("zigbee.0.00158d00049fd9ee.available"),
    },
    xioami_floor_right: {
      percent: new NumberValue("zigbee.0.00158d000477309a.battery"),
      voltage: new NumberValue("zigbee.0.00158d000477309a.voltage"),
      available: new BooleanValue("zigbee.0.00158d000477309a.available"),
    },
    xioami_floor_left: {
      percent: new NumberValue("zigbee.0.00158d00047e796c.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047e796c.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047e796c.available"),
    },
    xioami_guest_toilet_left: {
      percent: new NumberValue("zigbee.0.00158d00047e7a16.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047e7a16.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047e7a16.available"),
    },
    xioami_guest_toilet_right: {
      percent: new NumberValue("zigbee.0.00158d0004a03d10.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004a03d10.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004a03d10.available"),
    },
    xioami_fensterkontakt_kueche_klingel: {
      percent: new NumberValue("zigbee.0.00158d0002ec5554.battery"),
      voltage: new NumberValue("zigbee.0.00158d0002ec5554.voltage"),
      available: new BooleanValue("zigbee.0.00158d0002ec5554.available"),
    },
    xioami_kitchen_window: {
      percent: new NumberValue("zigbee.0.00158d000431445a.battery"),
      voltage: new NumberValue("zigbee.0.00158d000431445a.voltage"),
      available: new BooleanValue("zigbee.0.00158d000431445a.available"),
    },
    xioami_kitchen_door: {
      percent: new NumberValue("zigbee.0.00158d00047d0bcc.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047d0bcc.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047d0bcc.available"),
    },
    xioami_store_window: {
      percent: new NumberValue("zigbee.0.00158d0004773713.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004773713.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004773713.available"),
    },
    xioami_diner_window_right: {
      percent: new NumberValue("zigbee.0.00158d0002e3376c.battery"),
      voltage: new NumberValue("zigbee.0.00158d0002e3376c.voltage"),
      available: new BooleanValue("zigbee.0.00158d0002e3376c.available"),
    },
    xioami_diner_window_left: {
      percent: new NumberValue("zigbee.0.00158d000477238b.battery"),
      voltage: new NumberValue("zigbee.0.00158d000477238b.voltage"),
      available: new BooleanValue("zigbee.0.00158d000477238b.available"),
    },
    xioami_living_right: {
      percent: new NumberValue("zigbee.0.00158d00047c617c.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047c617c.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047c617c.available"),
    },
    xioami_living_center: {
      percent: new NumberValue("zigbee.0.00158d00047ebffb.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047ebffb.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047ebffb.available"),
    },
    xioami_living_left: {
      percent: new NumberValue("zigbee.0.00158d00047d480e.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047d480e.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047d480e.available"),
    },
    xioami_living_small: {
      percent: new NumberValue("zigbee.0.00158d0004a02290.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004a02290.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004a02290.available"),
    },
    xioami_bath_window: {
      percent: new NumberValue("zigbee.0.00158d00047d0d78.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047d0d78.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047d0d78.available"),
    },
    xioami_guest_window: {
      percent: new NumberValue("zigbee.0.00158d0004772546.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004772546.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004772546.available"),
    },
    xioami_sleeping_door: {
      percent: new NumberValue("zigbee.0.00158d0004522184.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004522184.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004522184.available"),
    },
    xioami_sleeping_window: {
      percent: new NumberValue("zigbee.0.00158d0004a027ee.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004a027ee.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004a027ee.available"),
    },
    xioami_children_window: {
      percent: new NumberValue("zigbee.0.00158d0004a0224b.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004a0224b.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004a0224b.available"),
    },
    xioami_store_og_right: {
      percent: new NumberValue("zigbee.0.00158d0004a0234e.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004a0234e.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004a0234e.available"),
    },
    xioami_store_og_left: {
      percent: new NumberValue("zigbee.0.00158d0004772531.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004772531.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004772531.available"),
    },
    xioami_attic_right: {
      percent: new NumberValue("zigbee.0.00158d0004314104.battery"),
      voltage: new NumberValue("zigbee.0.00158d0004314104.voltage"),
      available: new BooleanValue("zigbee.0.00158d0004314104.available"),
    },
    xioami_attic_left: {
      percent: new NumberValue("zigbee.0.00158d00047d0db9.battery"),
      voltage: new NumberValue("zigbee.0.00158d00047d0db9.voltage"),
      available: new BooleanValue("zigbee.0.00158d00047d0db9.available"),
    },
  },
  shutterAutoDownTime: {
    esszimmerLinksDelay: new NumberValue("0_userdata.0.Rolladen.Esszimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    kuecheFensterDelay: new NumberValue("0_userdata.0.Rolladen.Küche.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    schlafenTuerDelay: new NumberValue("0_userdata.0.Rolladen.Schlafzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang_Tür"),
    schlafenFensterDelay: new NumberValue("0_userdata.0.Rolladen.Schlafzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    kinderzimmerFensterDelay: new NumberValue("0_userdata.0.Rolladen.Kinderzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    badFensterDelay: new NumberValue("0_userdata.0.Rolladen.Bad.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    wohnzimmerEckeDelay: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    wohnzimmerLinksDelay: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    wohnzimmerMitteDelay: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    wohnzimmerRechtsDelay: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    kuecheTuerDelay: new NumberValue("0_userdata.0.Rolladen.Küche.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(Tür)"),
    abstellraumOgLinksDelay: new NumberValue("0_userdata.0.Rolladen.Abstellraum_OG.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(links)"),
    abstellraumOgRechtsDelay: new NumberValue("0_userdata.0.Rolladen.Abstellraum_OG.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(rechts)"),
    gaestezimmerFensterDelay: new NumberValue("0_userdata.0.Rolladen.Gästezimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang"),
    esszimmerLinksAuto: new BooleanValue("0_userdata.0.Rolladen.Esszimmer.Esszimmer_Rolladen_Zeitsteuerung"),
    gaestezimmerFensterAuto: new BooleanValue("0_userdata.0.Rolladen.Gästezimmer.Rollade_Auto_runter"),
    kuecheFensterAuto: new BooleanValue("0_userdata.0.Rolladen.Küche.Fenster_Rolladen_Zeitsteuerung"),
    schlafenTuerAuto: new BooleanValue("0_userdata.0.Rolladen.Schlafzimmer.Schlafzimmer_Rolladen_Zeitsteuerung"),
    schlafenFensterAuto: new BooleanValue("0_userdata.0.Rolladen.Schlafzimmer.Schlafzimmer_Rollade_Fenster_Zeitsteuerung"),
    kinderzimmerFensterAuto: new BooleanValue("0_userdata.0.Rolladen.Kinderzimmer.Rollade_automisch_runter"),
    badFensterAuto: new BooleanValue("0_userdata.0.Rolladen.Bad.Bad_Rolladen_Zeitsteuerung"),
    wohnzimmerEckeAuto: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung"),
    wohnzimmerLinksAuto: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung"),
    wohnzimmerMitteAuto: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung"),
    wohnzimmerRechtsAuto: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Wohnzimmer_Rolladen_Zeitsteuerung"),
    kuecheTuerAuto: new BooleanValue("0_userdata.0.Rolladen.Küche.Tür_Rolladen_Zeitsteuerung"),
    abstellraumOgLinksAuto: new BooleanValue("0_userdata.0.Rolladen.Abstellraum_OG.Abstellraum_OG_links_Rolladen_Zeitsteuerung_aktiv"),
    abstellraumOgRechtsAuto: new BooleanValue("0_userdata.0.Rolladen.Abstellraum_OG.Abstellraum_OG_rechts_Rolladen_Zeitsteuerung_aktiv"),
  },
  shutterAutoUp: {
    wohnzimmerEckeAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch"),
    wohnzimmerLinksAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch"),
    wohnzimmerMitteAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch"),
    wohnzimmerRechtsAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Wohnzimmer.Zeit_Rollade_hoch"),
    schlafenTuerAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Schlafzimmer.Zeit_Rollade_hoch_Tür"),
    schlafenFensterAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Schlafzimmer.Zeit_Rollade_hoch"),
    kuecheFensterAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Küche.Zeit_Rollade_hoch_Fenster"),
    kuecheTuerAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Küche.Zeit_Rollade_hoch_Tür"),
    kinderzimmerFensterAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Kinderzimmer.Zeit_Rollade_hoch"),
    esszimmerLinksAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Esszimmer.Zeit_Rollade_hoch"),
    badFensterAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Bad.Zeit_Rollade_hoch"),
    abstellraumOgRechtsAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Abstellraum_OG.Zeit_Rollade_hoch_rechts"),
    abstellraumOgLinksAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Abstellraum_OG.Zeit_Rollade_hoch_links"),
    gaestezimmerFensterAutoUpTime: new NumberValue("0_userdata.0.Rolladen.Gästezimmer.Zeit_Rollade_hoch"),
    abstellraumOgLinksAutoUp: new BooleanValue("0_userdata.0.Rolladen.Abstellraum_OG.Auto_hoch_links"),
    abstellraumOgRechtsAutoUp: new BooleanValue("0_userdata.0.Rolladen.Abstellraum_OG.Auto_hoch_rechts"),
    badFensterAutoUp: new BooleanValue("0_userdata.0.Rolladen.Bad.Rollade_Auto_hoch"),
    esszimmerLinksAutoUp: new BooleanValue("0_userdata.0.Rolladen.Esszimmer.Rollade_Auto_hoch"),
    gaestezimmerFensterAutoUp: new BooleanValue("0_userdata.0.Rolladen.Gästezimmer.Rollade_Auto_hoch"),
    kinderzimmerFensterAutoUp: new BooleanValue("0_userdata.0.Rolladen.Kinderzimmer.Rollade_auto_hoch"),
    kuecheTuerAutoUp: new BooleanValue("0_userdata.0.Rolladen.Küche.Rollade_auto_hoch_Tür"),
    kuecheFensterAutoUp: new BooleanValue("0_userdata.0.Rolladen.Küche.Rollade_auto_hoch_fenster"),
    schlafenFensterAutoUp: new BooleanValue("0_userdata.0.Rolladen.Schlafzimmer.Rollade_auto_hoch_fenster"),
    schlafenTuerAutoUp: new BooleanValue("0_userdata.0.Rolladen.Schlafzimmer.Rollade_auto_hoch_tuer"),
    wohnzimmerEckeAutoUp: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch"),
    wohnzimmerLinksAutoUp: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch"),
    wohnzimmerMitteAutoUp: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch"),
    wohnzimmerRechtsAutoUp: new BooleanValue("0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch"),
  },
  rolladen: {
    wohnzimmerMittePosition: new NumberValue("s7.1.DBs.DB1.B150"),
    wohnzimmerEckePosition: new NumberValue("s7.1.DBs.DB1.B152"),
    wohnzimmerLinksPosition: new NumberValue("s7.1.DBs.DB1.B159"),
    wohnzimmerRechtsPosition: new NumberValue("s7.1.DBs.DB1.B157"),
    kuecheTuerPosition: new NumberValue("s7.1.DBs.DB1.B129"),
    kuecheFensterPosition: new NumberValue("s7.1.DBs.DB1.B145"),
    esszimmerLinksPosition: new NumberValue("s7.1.DBs.DB1.B136"),
    kinderzimmerFensterPosition: new NumberValue("s7.1.DBs.DB1.B164"),
    schlafenTuerPosition: new NumberValue("s7.1.DBs.DB1.B169"),
    schlafenFensterPosition: new NumberValue("s7.2.DBs.DB1.B065"),
    abstellraumOgLinksPosition: new NumberValue("s7.2.DBs.DB1.B073"),
    abstellraumOgRechtsPosition: new NumberValue("s7.2.DBs.DB1.B057"),
    badFensterPosition: new NumberValue("s7.2.DBs.DB1.B078"),
    gaestezimmerFensterPosition: new NumberValue("s7.2.DBs.DB1.B150"),
  },
  timers: {
    timerAlive: new BooleanValue("alexa-timer-vis.0.all_Timer.alive"),
    1: {
      timeString: new StringValue("alexa-timer-vis.0.timer1.string_2"),
      timeEnd: new StringValue("alexa-timer-vis.0.timer1.TimeEnd"),
      timeStart: new StringValue("alexa-timer-vis.0.timer1.TimeStart"),
      device: new StringValue("alexa-timer-vis.0.timer1.InputDeviceName"),
      name: new StringValue("alexa-timer-vis.0.timer1.name"),
      initialTimer: new StringValue("alexa-timer-vis.0.timer1.initialTimer"),
    },
    2: {
      timeString: new StringValue("alexa-timer-vis.0.timer2.string_2"),
      timeEnd: new StringValue("alexa-timer-vis.0.timer2.TimeEnd"),
      timeStart: new StringValue("alexa-timer-vis.0.timer2.TimeStart"),
      device: new StringValue("alexa-timer-vis.0.timer2.InputDeviceName"),
      name: new StringValue("alexa-timer-vis.0.timer2.name"),
      initialTimer: new StringValue("alexa-timer-vis.0.timer2.initialTimer"),
    },
    3: {
      timeString: new StringValue("alexa-timer-vis.0.timer3.string_2"),
      timeEnd: new StringValue("alexa-timer-vis.0.timer3.TimeEnd"),
      timeStart: new StringValue("alexa-timer-vis.0.timer3.TimeStart"),
      device: new StringValue("alexa-timer-vis.0.timer3.InputDeviceName"),
      name: new StringValue("alexa-timer-vis.0.timer3.name"),
      initialTimer: new StringValue("alexa-timer-vis.0.timer3.initialTimer"),
    },
    4: {
      timeString: new StringValue("alexa-timer-vis.0.timer4.string_2"),
      timeEnd: new StringValue("alexa-timer-vis.0.timer4.TimeEnd"),
      timeStart: new StringValue("alexa-timer-vis.0.timer4.TimeStart"),
      device: new StringValue("alexa-timer-vis.0.timer4.InputDeviceName"),
      name: new StringValue("alexa-timer-vis.0.timer4.name"),
      initialTimer: new StringValue("alexa-timer-vis.0.timer4.initialTimer"),
    },
  },
  tankerKoenig: {
    cheapestName: new StringValue("tankerkoenig.0.stations.cheapest.e5.name"),
    cheapestFullStreet: new StringValue("tankerkoenig.0.stations.cheapest.e5.fullStreet"),
    cheapestPrice: new NumberValue("tankerkoenig.0.stations.cheapest.e5.feed"),
    jsonTable: new JsonValue<TankerkoenigStation[]>("tankerkoenig.0.stations.jsonTable"),
  },
  fenster: {
    haustuer: new BooleanValue("zigbee.0.00158d00049fd9ee.opened"),
    wohnzimmerEcke: new BooleanValue("alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster klein open.ACTUAL"),
    wohnzimmerLinks: new BooleanValue("alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster links open.ACTUAL"),
    wohnzimmerRechts: new BooleanValue("alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL"),
    wohnzimmerMitte: new BooleanValue("alias.0.Wohnzimmer.Xiaomi AqaraSensoren.Fenster mitte open.ACTUAL"),
    gaesteWcRechts: new BooleanValue("alias.0.Gäste WC.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL"),
    gaesteWcLinks: new BooleanValue("alias.0.Gäste WC.Xiaomi AqaraSensoren.Fenster links open.ACTUAL"),
    bueroFenster: new BooleanValue("zigbee.0.00158d0003cb431e.opened"),
    schlafenFenster: new BooleanValue("alias.0.Schlafzimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL"),
    schlafenTuer: new BooleanValue("alias.0.Schlafzimmer.Xiaomi AqaraSensoren.Tür open.ACTUAL"),
    kellerTuer: new BooleanValue("alias.0.Keller.Xiaomi AqaraSensoren.Tür open.Kellertür open"),
    kinderzimmerFenster: new BooleanValue("alias.0.Kinderzimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL"),
    badFenster: new BooleanValue("alias.0.Bad.Xiaomi AqaraSensoren.Fenster open.ACTUAL"),
    gaestezimmerFenster: new BooleanValue("alias.0.Gästezimmer.Xiaomi AqaraSensoren.Fenster open.ACTUAL"),
    esszimmerLinks: new BooleanValue("alias.0.Esszimmer.Xiaomi AqaraSensoren.Links open.ACTUAL"),
    esszimmerRechts: new BooleanValue("alias.0.Esszimmer.Xiaomi AqaraSensoren.Rechts open.ACTUAL"),
    kuecheTuer: new BooleanValue("alias.0.Küche.Xiaomi AqaraSensoren.Tür open.ACTUAL"),
    kuecheFenster: new BooleanValue("alias.0.Küche.Xiaomi AqaraSensoren.Fenster open.ACTUAL"),
    abstellraumFenster: new BooleanValue("alias.0.Abstellraum.Xiaomi AqaraSensoren.Fenster open.ACTUAL"),
    abstellraumOgLinks: new BooleanValue("alias.0.Abstellraum OG.Xiaomi AqaraSensoren.Fenster links open.ACTUAL"),
    abstellraumOgRechts: new BooleanValue("alias.0.Abstellraum OG.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL"),
    dachbodenLinks: new BooleanValue("alias.0.Dachboden.Xiaomi AqaraSensoren.Fenster links open.ACTUAL"),
    dachbodenRechts: new BooleanValue("alias.0.Dachboden.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL"),
    flurLinks: new BooleanValue("alias.0.Flur.Xiaomi AqaraSensoren.Fenster links open.ACTUAL"),
    flurRechts: new BooleanValue("alias.0.Flur.Xiaomi AqaraSensoren.Fenster rechts open.ACTUAL"),
    kellerFlurFenster: new BooleanValue("alias.0.Keller.Xiaomi AqaraSensoren.Keller Treppe.Fenster.KellerTreppe Fenster"),
  },
  styles: {
    calendarStyle: new JsonValue<JSONStyle[]>("0_userdata.0.vis.calendar_styles"),
  },
  position: {
    michaelCoordinates: new StringValue("life360ng.0.people.afa1605e-1339-4bbc-921e-37b7774a75ce.gps-coordinates"),
  },
  pool: {
    heaterState: new BooleanValue("midas-aquatemp.0.state"),
    heaterOnline: new BooleanValue("midas-aquatemp.0.online"),
    tempSet: new NumberValue("midas-aquatemp.0.tempSet"),
    consumption: new NumberValue("midas-aquatemp.0.consumption"),
    tempIn: new NumberValue("midas-aquatemp.0.tempIn"),
    tempOut: new NumberValue("midas-aquatemp.0.tempOut"),
    rotor: new NumberValue("midas-aquatemp.0.rotor"),
    mode: new NumberValue("midas-aquatemp.0.mode"),
    status: new BooleanValue("midas-aquatemp.0.info.connection"),
    silent: new BooleanValue("midas-aquatemp.0.silent"),
    poolPumpPower: new NumberValue("shelly.0.SHPLG-S#4022D889A587#1.Relay0.Power"),
    poolPumpSwitch: new BooleanValue("shelly.0.SHPLG-S#4022D889A587#1.Relay0.Switch"),
    heaterScriptActivateJSON: new JsonValue<HeatingPumpScriptJson>("0_userdata.0.Wärmepumpe.Wärmepumpe_schalten_script"),
    heaterSilentScriptJSON: new JsonValue<HeatingPumpSilentJSON>("0_userdata.0.Wärmepumpe.SilentModeScriptJson"),
  },
  phone: {
    ringing: new BooleanValue("tr-064.0.callmonitor.ringing"),
    lastCallTimestamp: new StringValue("tr-064.0.callmonitor.lastCall.timestamp"),
    lastCallerName: new StringValue("tr-064.0.callmonitor.lastCall.callerName"),
    lastCaller: new StringValue("tr-064.0.callmonitor.lastCall.caller"),
    lastDuration: new StringValue("tr-064.0.callmonitor.lastCall.duration"),
    caller: new StringValue("tr-064.0.callmonitor.inbound.caller"),
    callerName: new StringValue("tr-064.0.callmonitor.inbound.callerName"),
    callerTimestamp: new StringValue("tr-064.0.callmonitor.inbound.timestamp"),
  },
  lights: {
    Wohnzimmer: new BooleanValue("sonoff.0.Sonoff_Wohnzimmer.POWER"),
    Wohnzimmer_Ecklampe: new BooleanValue("s7.2.DBs.DB1.M6"),
    Weihnachtsbaum: new BooleanValue("zigbee.0.a4c138d35583a3d7.state"),
    Dachboden: new BooleanValue("sonoff.0.Sonoff_Dachboden.POWER"),
    Abstellraum_OG: new BooleanValue("sonoff.0.Sonoff_OG_Abstellraum.POWER"),
    Buero: new BooleanValue("sonoff.0.Sonoff_Keller_Michi.POWER"),
    Buero_Schreibtisch: new BooleanValue("tuya.0.bfec013e9034a47a12o5so.20"),
  },
  lightsAdditive: {
    Wohnzimmer_Ecklampe: new BooleanValue("s7.2.DBs.DB1.Q11"),
  },
  logs: {
    error: new JsonValue<Log[]>("logparser.0.filters.Error.json"),
    info: new JsonValue<Log[]>("logparser.0.filters.Info.json"),
    warning: new JsonValue<Log[]>("logparser.0.filters.Warn.json"),
    heatPump: new JsonValue<Log[]>("logparser.0.filters.Wärmepumpe.json"),
  },
  infos: {
    updatesJson: new JsonValue<UpdatesAsJSON>("admin.0.info.updatesJson"),
    updatesNumber: new NumberValue("admin.0.info.updatesNumber"),
    lastUpdateCheck: new StringValue("admin.0.info.lastUpdateCheck"),
    newsFeeds: new JsonValue<NewsFeed[]>("admin.0.info.newsFeed"),
  },
  hmip: {
    children_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55E2C.channels.1.valveActualTemperature"),
    children_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55E2C.channels.1.valvePosition"),
    floor_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A499E347E.channels.1.valveActualTemperature"),
    floor_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A499E347E.channels.1.valvePosition"),
    living_right_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55C21.channels.1.valveActualTemperature"),
    living_right_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55C21.channels.1.valvePosition"),
    living_left_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A499E3491.channels.1.valveActualTemperature"),
    living_left_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A499E3491.channels.1.valvePosition"),
    kitchen_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A499E49C4.channels.1.valveActualTemperature"),
    kitchen_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A499E49C4.channels.1.valvePosition"),
    guest_wc_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A499E4A06.channels.1.valveActualTemperature"),
    guest_wc_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A499E4A06.channels.1.valvePosition"),
    bath_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55A77.channels.1.valveActualTemperature"),
    bath_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55A77.channels.1.valvePosition"),
    sleeping_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55AEF.channels.1.valveActualTemperature"),
    sleeping_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55AEF.channels.1.valvePosition"),
    dining_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55AF0.channels.1.valveActualTemperature"),
    dining_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55AF0.channels.1.valvePosition"),
    washing_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55C1D.channels.1.valveActualTemperature"),
    washing_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55C1D.channels.1.valvePosition"),
    guest_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55C2A.channels.1.valveActualTemperature"),
    guest_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55C2A.channels.1.valvePosition"),
    office_valveActualTemp: new NumberValue("hmip.0.devices.3014F711A000201A49A55C45.channels.1.valveActualTemperature"),
    office_valvePosition: new NumberValue("hmip.0.devices.3014F711A000201A49A55C45.channels.1.valvePosition"),
  },
  heating: {
    automatic: new BooleanValue("s7.0.DBs.DB1.I6_-_NQ5"),
    level: new BooleanValue("s7.0.DBs.DB1.I5_-_NQ2"),
    active: new BooleanValue("s7.0.DBs.DB1.NQ13"),
    autoSolar: new BooleanValue("s7.0.DBs.DB1.NQ15"),
    heatingTemperature: new NumberValue("s7.0.DBs.DB1.B059"),
    heatingSolar: new NumberValue("s7.0.DBs.DB1.B054"),
    heatingBuffer: new NumberValue("s7.0.DBs.DB1.B068"),
    heatingBufferMiddle: new NumberValue("mqtt.0.oeg.43_T6_Puffer_Mitte_Ist-Wert"),
    heatingBufferTop: new NumberValue("mqtt.0.oeg.42_T5_Puffer_Brauchwasser_Ist-Wert"),
    solarMaxToday: new NumberValue("s7.0.DBs.DB1.B076"),
    solarMax: new NumberValue("s7.0.DBs.DB1.B085"),
    pelletExist: new BooleanValue("s7.0.DBs.DB1.NQ12"),
    watcherAdmitter: new BooleanValue("s7.0.DBs.DB1.I3_-_NQ3"),
    tempPelletBuffer: new BooleanValue("s7.0.DBs.DB1.I4_-_NQ4"),
    confirmMessage: new BooleanValue("s7.0.DBs.DB1.NQ14"),
    snail: new BooleanValue("s7.0.DBs.DB1.I1_-_NQ1"),
    spiral: new BooleanValue("s7.0.DBs.DB1.NQ8"),
    maxTimeToFill: new NumberValue("s7.0.DBs.DB1.B004"),
    offsetFilling: new NumberValue("s7.0.DBs.DB1.B008"),
    tempPumpOn: new NumberValue("s7.0.DBs.DB1.B061"),
    tempPumpOff: new NumberValue("s7.0.DBs.DB1.B061_2"),
    diffSolarBuffer: new NumberValue("s7.0.DBs.DB1.B067"),
    minFillTemp: new NumberValue("s7.0.DBs.DB1.B069"),
    maxFillTemp: new NumberValue("s7.0.DBs.DB1.B056"),
    solarPump: new BooleanValue("s7.0.DBs.DB1.Q3_-_NQ10"),
    heatingPump: new BooleanValue("s7.0.DBs.DB1.Q4_-_NQ11"),
  },
  energy: {
    Waschmaschine: new NumberValue("sonoff.0.Steckdose_Waschmaschine .ENERGY_Power"),
    Kuehltruhe: new NumberValue("sonoff.0.Tasmota Kühltruhe.ENERGY_Power"),
    Rack: new NumberValue("sonoff.0.Tasmota Server.ENERGY_Power"),
    energyReceived: new NumberValue("0_userdata.0.Photovoltaik.Bezug_Tag"),
    energyReturned: new NumberValue("0_userdata.0.Photovoltaik.Einspeisung_Tag"),
  },
  calendar: {
    table: new JsonValue<CalendarDayType[]>("ical.1.data.table"),
  },
  airConditioners: {
    schlafenOnline: new BooleanValue("tuya.0.bf371cfe643bf102afauv6.online"),
    schlafenPowerStatus: new BooleanValue("tuya.0.bf371cfe643bf102afauv6.1"),
    schlafenPower: new NumberValue("shelly.0.SHPLG-S#4022D8894549#1.Relay0.Power"),
    schlafenIsTemp: new NumberValue("tuya.0.bf371cfe643bf102afauv6.8"),
    schlafenSetTemp: new NumberValue("tuya.0.bf371cfe643bf102afauv6.5"),
    childOnline: new BooleanValue("tuya.0.bf57f6b83543b4f45dwh13.online"),
    childPowerStatus: new BooleanValue("tuya.0.bf57f6b83543b4f45dwh13.1"),
    childPower: new NumberValue("shelly.0.SHPLG-S#4022D8895174#1.Relay0.Power"),
    childIsTemp: new NumberValue("tuya.0.bf57f6b83543b4f45dwh13.8"),
    childSetTemp: new NumberValue("tuya.0.bf57f6b83543b4f45dwh13.5"),
  },
  landroid: {
    battery: new NumberValue("worx.0.202330294701005409AD.mower.batteryState"),
    totalDistance: new NumberValue("worx.0.202330294701005409AD.mower.totalDistance"),
    totalBladeTime: new NumberValue("worx.0.202330294701005409AD.mower.totalBladeTime"),
    status: new NumberValue("worx.0.202330294701005409AD.mower.status"),
    online: new BooleanValue("worx.0.202330294701005409AD.mower.online"),
    firmware: new StringValue("worx.0.202330294701005409AD.mower.firmware"),
    error: new NumberValue("worx.0.202330294701005409AD.mower.error"),
    edgecut: new BooleanValue("worx.0.202330294701005409AD.mower.edgecut"),
    batteryCharging: new BooleanValue("worx.0.202330294701005409AD.mower.batteryCharging"),
  },
  trash: {
    json: new JsonValue<TrashType[]>("trashschedule.0.type.json"),
  },
  alexaLists: {
    shoppingListActive: new JsonValue<AlexaList[]>("alexa-shoppinglist.0.list_activ"),
    michaelsTodoList: new JsonValue<AlexaList[]>("alexa-shoppinglist.1.list_activ"),
  },
  time: {
    sonnenuntergang: new BooleanValue("0_userdata.0.Rolladen.Zeit_Rollade_auto_herunter"),
  },
  holiday: {
    urlaubAktiv: new BooleanValue("0_userdata.0.Urlaub.Urlaub_aktiv"),
  },
  windowGlobal: {
    fensterOffen: new BooleanValue("0_userdata.0.Fenster.Sind_Fenster_offen"),
  },
  heatingControl: {
    profile: new NumberValue("heatingcontrol.0.CurrentProfile"),
    room: new NumberValue("heatingcontrol.0.vis.ChoosenRoom"),
    profileText: new StringValue("heatingcontrol.0.vis.ProfileValueListText"),
    profileValue: new StringValue("heatingcontrol.0.vis.ProfileValueListValue"),
    usedRoom: new StringValue("heatingcontrol.0.info.UsedRooms"),
    periodActive: new BooleanValue("heatingcontrol.0.HeatingPeriodActive"),
    publicHoliday: new BooleanValue("heatingcontrol.0.PublicHolidyToday"),
    present: new BooleanValue("heatingcontrol.0.Present"),
    partyNow: new BooleanValue("heatingcontrol.0.PartyNow"),
    guestsPresent: new BooleanValue("heatingcontrol.0.GuestsPresent"),
    holidayPresent: new BooleanValue("heatingcontrol.0.HolidayPresent"),
    vacationAbsent: new BooleanValue("heatingcontrol.0.VacationAbsent"),
    guestIncrease: new NumberValue("heatingcontrol.0.vis.TempDecreaseValues.GuestIncrease"),
    partyDecrease: new NumberValue("heatingcontrol.0.vis.TempDecreaseValues.PartyDecrease"),
    absentDecrease: new NumberValue("heatingcontrol.0.vis.TempDecreaseValues.AbsentDecrease"),
    vacationAbsentDecrease: new NumberValue("heatingcontrol.0.vis.TempDecreaseValues.VacationAbsentDecrease"),
    windowOpenDecrease: new NumberValue("heatingcontrol.0.vis.TempDecreaseValues.WindowOpenDecrease"),
    temperatureOverrideTemp: new NumberValue("heatingcontrol.0.vis.RoomValues.TemperaturOverride"),
    temperatureOverrideTime: new NumberValue("heatingcontrol.0.vis.RoomValues.TemperaturOverrideTime"),
    minimumTemperature: new NumberValue("heatingcontrol.0.vis.RoomValues.MinimumTemperature"),
    openWindowCount: new NumberValue("heatingcontrol.0.vis.OpenWindowRoomCount"),
    windowOpenHtmlTable: new StringValue("heatingcontrol.0.vis.WindowStatesHtmlTable"),
    statusRoom: new StringValue("0_userdata.0.Heizung.heatingcontrol.Status_Zimmer_state"),
    sollTemp1: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Soll_Temp"),
    sollTemp2: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Soll_Temp_2"),
    tempRegler1: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Temperatur_am_Regler"),
    tempRegler2: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Temperatur_am_Regler_2"),
    ventil1: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Ventilstellung"),
    ventil2: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Ventilstellung_2"),
    tempSensor: new NumberValue("0_userdata.0.Heizung.heatingcontrol.Temperatur_am_Raumsensor"),
    roomState: new StringValue("0_userdata.0.Heizung.heatingcontrol.Room_State"),
    visRoomStates: new StringValue("heatingcontrol.0.vis.RoomStatesHtmlTable"),
    timeSlotBad: new NumberValue("heatingcontrol.0.Rooms.Bad.ActiveTimeSlot"),
  },
  heatingControlDay: {
    Mon: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Mon.Periods.5.time"),
      },
    },
    Tue: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Tue.Periods.5.time"),
      },
    },
    Wed: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Wed.Periods.5.time"),
      },
    },
    Thu: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Thu.Periods.5.time"),
      },
    },
    Fri: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Fri.Periods.5.time"),
      },
    },
    Sat: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sat.Periods.5.time"),
      },
    },
    Sun: {
      "1": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.1.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.1.time"),
      },
      "2": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.2.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.2.time"),
      },
      "3": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.3.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.3.time"),
      },
      "4": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.4.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.4.time"),
      },
      "5": {
        temp: new NumberValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.5.Temperature"),
        time: new StringValue("heatingcontrol.0.vis.ProfileTypes.Sun.Periods.5.time"),
      },
    },
  },
};

export type Timer = (typeof iobrokerTree)["timers"][1];
export type Timers = Omit<(typeof iobrokerTree)["timers"], "timerAlive">;
