import { IdToSubscribe, Shutter } from "@/types";

export const shutterAutoDownTime: IdToSubscribe<Shutter> = {
  // Zeitversatz Rolladen Auto herunter fahren
  objectNameInStore: "shutterAutoDownTime",
  value: [
    {
      id: "0_userdata.0.Rolladen.Esszimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "esszimmer",
      subKey: "links",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Küche.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "kueche",
      subKey: "fenster",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Schlafzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "schlafen",
      subKey: "fenster",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Schlafzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "schlafen",
      subKey: "tuer",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Kinderzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "kinderzimmer",
      subKey: "fenster",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Bad.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "bad",
      subKey: "fenster",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "wohnzimmer",
      subKey: "ecke",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "wohnzimmer",
      subKey: "links",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "wohnzimmer",
      subKey: "mittig",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "wohnzimmer",
      subKey: "rechts",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Küche.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(Tür)",
      room: "kueche",
      subKey: "tuer",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Abstellraum_OG.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(links)",
      room: "abstellraumog",
      subKey: "links",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Abstellraum_OG.Zeitversatz_herunterfahren_zum_Sonnenuntergang_(rechts)",
      room: "abstellraumog",
      subKey: "rechts",
      subKeyAdditive: "Delay",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Gästezimmer.Zeitversatz_herunterfahren_zum_Sonnenuntergang",
      room: "gaestezimmer",
      subKey: "fenster",
      subKeyAdditive: "Delay",
      saveId: true,
    },
  ],
};
