export const shutterAutoUp: IdToSubscribe = {
  // Auto hoch aktiv
  objectNameInStore: "shutterAutoUp",
  value: [
    {
      id: "0_userdata.0.Rolladen.Abstellraum_OG.Auto_hoch_links",
      room: "abstellraumog",
      subKey: "links",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Abstellraum_OG.Auto_hoch_rechts",
      room: "abstellraumog",
      subKey: "rechts",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Bad.Rollade_Auto_hoch",
      room: "bad",
      subKey: "fenster",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Esszimmer.Rollade_Auto_hoch",
      room: "esszimmer",
      subKey: "links",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Gästezimmer.Rollade_Auto_hoch",
      room: "gaestezimmer",
      subKey: "fenster",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Kinderzimmer.Rollade_auto_hoch",
      room: "kinderzimmer",
      subKey: "fenster",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Küche.Rollade_auto_hoch_Tür",
      room: "kueche",
      subKey: "tuer",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Küche.Rollade_auto_hoch_fenster",
      room: "kueche",
      subKey: "fenster",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Schlafzimmer.Rollade_auto_hoch_fenster",
      room: "schlafen",
      subKey: "fenster",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },    {
      id: "0_userdata.0.Rolladen.Schlafzimmer.Rollade_auto_hoch_tuer",
      room: "schlafen",
      subKey: "tuer",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },   
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch",
      room: "wohnzimmer",
      subKey: "ecke",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch",
      room: "wohnzimmer",
      subKey: "links",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch",
      room: "wohnzimmer",
      subKey: "mittig",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
    {
      id: "0_userdata.0.Rolladen.Wohnzimmer.Rollade_auto_hoch",
      room: "wohnzimmer",
      subKey: "rechts",
      subKeyAdditive: "AutoUp",
      saveId: true,
    },
  ],
};
